# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField(max_length=1024, unique=True)),
                ('title', models.TextField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('icon', models.TextField(blank=True, max_length=512, null=True)),
                ('in_header', models.IntegerField()),
                ('in_footer', models.IntegerField()),
                ('in_contact', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
