# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 10:26
from __future__ import unicode_literals

from django.db import migrations
import json


def fill_from_mock(apps, schema_editor):
    try:
        with open('mock/manager/public_link_list.json') as f:
            content = f.read()
            f.close()
    except IOError:
        content = '[]'
    records = json.loads(content)

    PublicLink = apps.get_model("manager", "PublicLink")
    PublicLink.objects.all().delete()
    for record in records:
        item, created = PublicLink.objects.get_or_create(src=record['src'], title=record['title'],
                                                         description=record['description'],
                                                         icon=record['icon'],
                                                         in_header=record['in_header'],
                                                         in_footer=record['in_footer'],
                                                         in_contact=record['in_contact'])


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0003_meta_tag_fill_from_mock'),
    ]

    operations = [
        migrations.RunPython(fill_from_mock),
    ]
