# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_public_link_fill_from_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='in_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='in_footer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='in_header',
            field=models.IntegerField(default=0),
        ),
    ]
