# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='comment',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='only_update',
            field=models.IntegerField(default=0),
        ),
    ]
