# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


def copy_to_translate(apps, schema_editor):
    from project import settings

    MetaTag = apps.get_model("manager", "MetaTag")
    fields = ['attributes', 'content']

    items = MetaTag.objects.all()
    for (lang, title) in settings.LANGUAGES:
        for item in items:
            for field in fields:
                setattr(item, '%s_%s' % (field, lang), getattr(item, field))
            item.save()

    Properties = apps.get_model("manager", "Properties")
    fields = ['comment', 'value']

    items = Properties.objects.all()
    for (lang, title) in settings.LANGUAGES:
        for item in items:
            for field in fields:
                setattr(item, '%s_%s' % (field, lang), getattr(item, field))
            item.save()

    PublicLink = apps.get_model("manager", "PublicLink")
    fields = ['description', 'title']

    items = PublicLink.objects.all()
    for (lang, title) in settings.LANGUAGES:
        for item in items:
            for field in fields:
                setattr(item, '%s_%s' % (field, lang), getattr(item, field))
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0009_htmlcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='attributes_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='metatag',
            name='attributes_ru',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='metatag',
            name='content_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='metatag',
            name='content_ru',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='comment_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='comment_ru',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='value_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='value_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='description_ru',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='title_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='title_ru',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(copy_to_translate),
    ]
