language: node_js
node_js:
- '5.7.1'
sudo: required
install:
- source scripts/install.sh
before_script:
- source scripts/build.sh
script:
- nohup bash scripts/server.sh >>/dev/null 2>>/dev/null &
- source scripts/test.sh