# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('src', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
