# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


def copy_to_translate(apps, schema_editor):
    from project import settings

    File = apps.get_model("file", "File")
    fields = ['comment']

    items = File.objects.all()
    for (lang, title) in settings.LANGUAGES:
        for item in items:
            for field in fields:
                setattr(item,'%s_%s' % (field, lang),getattr(item, field))
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('file', '0002_fill_from_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='comment_ru',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(copy_to_translate),
    ]
