# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 17:41
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
import json


def fill_from_fixtures(apps, schema_editor):
    try:
        with open('app/myauth/fixtures/users.json') as f:
            content = f.read()
            f.close()
    except IOError:
        content = '[]'
    records = json.loads(content)

    for record in records:
        try:
            password = record['userData']['password']
        except:
            password = record['userData']['email']

        try:
            username = record['userData']['username']
        except:
            username = record['userData']['email']

        try:
            first_name = record['userData']['firstname']
        except:
            first_name = None

        try:
            last_name = record['userData']['lastname']
        except:
            last_name = None

        try:
            roles = record['userData']['roles']
        except:
            roles = []

        is_admin = False
        is_staff = False

        for role in roles:
            if role == 'user':
                is_staff = True
            if role == 'admin':
                is_admin = True

        try:
            user = User.objects.get(email=record['userData']['email'])
        except User.DoesNotExist:
            user = User.objects.create_user(email=record['userData']['email'], password=password, username=username)
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            user.first_name = first_name
            user.last_name = last_name
            user.is_staff = is_staff
            user.is_superuser = is_admin
            user.is_active = is_staff or is_admin
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_from_fixtures),
    ]
